### ISSUE TITLE
Secure Environment Variables

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-travis#11]
http://docs.travis-ci.com/user/environment-variables/
```sh
gem install travis
cd my_project
travis encrypt MY_SECRET_ENV=super_secret --add env.matrix
```

If you see a permissions error while attempting to install the ***travis*** **ruby gem**, 
we recommend using **rvm** to install the latest ruby (on your user's path) first then try again:

```sh
\curl -L https://get.rvm.io | bash -s stable --ruby
rvm install current && rvm use current
gem install travis
```
See: http://stackoverflow.com/a/14182172/1148249

**Comment by iteles** [comment]
:+1: A note on what environment variables are and why they are needed will also be useful to beginners as part of this update

**Comment by nelsonic** [comment]
@iteles agreed. I've added it to my _personal_ backlog https://github.com/nelsonic/node-js-by-example/issues/16 and will get to it shortly  (in "_The Book_") :wink:

For now, we just needed to hide the keys on Travis. :+1:

**Comment by rjmk** [comment]
Though the docs suggest adding to the env.matrix, I *think* this will cause a different build to be run for each secure environment variable, with only one variable exported each time. `--add env.global` may be a better bet.

**Comment by nelsonic** [comment]
Spot on @rjmk 
see: https://github.com/dwyl/tudo/blob/a98286e759f9b097e84058f071cc7df5e0645fc8/.travis.yml#L4-L6

**Comment by rjmk** [comment]
Awesome :+1:

(And also awesome! Looking forward to some serious #dwyling next week!)

**Comment by nelsonic** [comment]
We are going to get up to some fun things next week! #**dwyl** #**GetExcited**! :stuck_out_tongue_winking_eye:

**Comment by iteles** [comment]
https://github.com/dwyl/learn-environment-variables :ok_hand: :ok_hand:
