### ISSUE TITLE
Tweet the update

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-travis#13]
And post link here as per PR https://github.com/dwyl/learn-travis/pull/12.

**Comment by iteles** [comment]
Proposed tweet:
> Using Continuous Integration to test your @nodejs builds?
We updated our @TravisCI tutorial! https://github.com/dwyl/learn-travis/

@nelsonic Had to cut a whole bunch of words but liked where your original was going.

**Comment by iteles** [comment]
https://twitter.com/dwylhq/status/636973678358609920 
We can always tweet about it again tomorrow! :blush:

**Comment by Fl4m3Ph03n1x** [comment]
Should we tweet something every time this tutorial gets updated ?

**Comment by iteles** [comment]
@Fl4m3Ph03n1x That was a pretty sizeable update, so worth a tweet. (thanks for reminding us this was still open!)

I'm closing this issue, but certainly if it's brought up to date again with a nice refresh, we should tweet again 😊

**Comment by Fl4m3Ph03n1x** [comment]
About that nice refresh: https://github.com/dwyl/learn-travis/issues/23
Let me know your thoughts ! :D
