### ISSUE TITLE
Continuous Integration Diagram

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-travis#17]
One of the things that is _sorely_ lacking in this tutorial is a _Diagram_ explaining what CI is ... 
this was noted in: [`https://github.com/dwyl/learn-travis#future`](https://github.com/dwyl/learn-travis/tree/c3f5bdcf749864bd2e0cc61e03919a76a4163a5d#future)

@jjperezaguinaga has _crafted_ a _superb_ diagram to illustrate Continuous Integration:
https://github.com/jjperezaguinaga/diagrams

![image](https://cloud.githubusercontent.com/assets/194400/20029289/4f144248-a340-11e6-9841-eee32728237b.png)
[Click the image to enlarge]
Source: https://github.com/jjperezaguinaga/diagrams/blob/master/diagrams/CI_CD.png

This is _almost_ exactly what I had in mind to illustrate the concept!
If I could _request_ a change it would be:
+ [ ] (_temporarily_) remove the continuous deployment step and instead focus on the Pull Request review workflow. (_we can explain continuous delivery at the `end` of the tutorial!_)
+ [ ] Explain that the CI should have all the necessary tests to confirm that the change will work in "production" and should mimic the production environment as closely as possible.

**Comment by jjperezaguinaga** [comment]
Hey @nelsonic, I think I still have the source files of the diagram, and well, I think I can update it to fit the whole CI part you are looking for. Let me fix it up.

**Comment by jjperezaguinaga** [comment]
![travis](https://cloud.githubusercontent.com/assets/1128312/20186823/ddfdbb9e-a771-11e6-9e99-4720e7b60f53.png)

Here's an updated version, which might reflect better what a CI / Travis does.

**Comment by jjperezaguinaga** [comment]
Here's the .EPS inside a zip file (really Github), feel free to modify it as you needed, in terms of text or whatever you might feel do best. Let me know if you prefer a PSD or PDF.
[Travis.eps.zip](https://github.com/dwyl/learn-travis/files/583989/Travis.eps.zip)

**Comment by nelsonic** [comment]
@jjperezaguinaga that's _amazing_ thanks! 🎉

**Comment by Jbarget** [comment]
@nelsonic whats the `help wanted` on this issue? It looks to me like the 2 checkboxes in your first comment are satisfied?

**Comment by nelsonic** [comment]
@Jbarget yeah, @jjperezaguinaga's updated diagram is 😍 
If we can just PR an update to the Readme we can consider this "done".
