### ISSUE TITLE
remove /images directory from repo to avoid encouraging people to add images to repos!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-travis#24]
At present there is an `/images` directory in the project:
![image](https://user-images.githubusercontent.com/194400/28815360-0c91d00c-7699-11e7-8c75-55f741a95a95.png)
https://github.com/dwyl/learn-travis/tree/a597ff014c145bd16e3827294b1cd9d8c9c86a73/images
![image](https://user-images.githubusercontent.com/194400/28815378-1cfdba3c-7699-11e7-8a7f-a8aac04a6597.png)

I _used_ to think that storing the image _file_ (_binary_) in the repository was a _good_ way of including images in a README.md ... I was _wrong_. The most effective way is to _upload_ the image to GitHub's CDN and then include a link to it in the markdown.

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/28815447-5458823c-7699-11e7-8c65-bcf9e4569388.png)

![image](https://user-images.githubusercontent.com/194400/28815478-6b49c546-7699-11e7-9bc1-fe1ec36e4967.png)

![image](https://user-images.githubusercontent.com/194400/28815493-7a9b1be4-7699-11e7-8f67-36b547bac915.png)

![image](https://user-images.githubusercontent.com/194400/28815577-bd0922e6-7699-11e7-90ea-ba891933f2ce.png)

![image](https://user-images.githubusercontent.com/194400/28815609-d7ec720c-7699-11e7-9376-56d438b1d2d8.png)

![image](https://user-images.githubusercontent.com/194400/28816018-33a38120-769b-11e7-9f2f-28b7e325e9ed.png)

![image](https://user-images.githubusercontent.com/194400/28816007-2d303ec8-769b-11e7-8d75-8d1fbd93592c.png)

![image](https://user-images.githubusercontent.com/194400/28816067-5a2c99ee-769b-11e7-92da-c9187e0c8aa2.png)

![image](https://user-images.githubusercontent.com/194400/28816106-7ed7e1c2-769b-11e7-9601-39de2ec31e62.png)

**Comment by Fl4m3Ph03n1x** [comment]
Why do we want to keep people from adding images?
I mean, a good schematic is always nice, right?

**Comment by nelsonic** [comment]
@Fl4m3Ph03n1x perhaps I did not make this clear.
I _agree_ that images are a great form of communication.
There is no advantage to bloating a git/GitHub repository with images 
because their _binary_ nature is not easy to track changes as text.
