### ISSUE TITLE
disable npm test

### ISSUE THREAD

**Issue by shanalikhan** [dwyl/learn-travis#35]
what do we need to write to disable the `npm test` in travis.yml

**Comment by nelsonic** [comment]
@shanalikhan I don't _understand_ the question. 
Would you not be better off disabling the build on Travis-CI UI?

**Comment by nelsonic** [comment]
@shanalikhan try adding the following line to your `.travis.yml` file:
```yml
script: echo "npm test temporarily disabled"
```

See: https://travis-ci.org/dwyl/learn-travis/jobs/338953975#L515-L519

**Comment by nelsonic** [comment]
@shanalikhan did that approach work for you...? 🤔

**Comment by shanalikhan** [comment]
Yes thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by redplane** [comment]
I think `npm test` should be disabled by default.
Previously, we had to write `npm test` command ourselves, but it was OK.
Another CI framework, they don't run `npm test`. This will make travis ci to be consitent.
