### ISSUE TITLE
Hitcount badge error.

### ISSUE THREAD

**Issue by Rupeshiya** [dwyl/learn-travis#45]
@nelsonic look at it.
![screenshot 18](https://user-images.githubusercontent.com/31209617/44002790-3219f822-9e66-11e8-8438-3e0ee36fa02d.png)

**Comment by nelsonic** [comment]
@Rupeshiya thank you for opening this issue ... 👍 
SSL Certificate renewal ... 🙄 
it's on my "Todo List" for when I'm back at my desk on Tuesday: https://github.com/dwyl/learn-devops/issues/44
(_hopefully the badge being "broken" does not detract too much from the content for the next  36h ..._)

**Comment by nelsonic** [comment]
Closing as was fixed a `while` ago ... ✅
