### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by lex111** [dwyl/learn-travis#46]
I want to translate this guide into Russian, how can I do this?

**Comment by nelsonic** [comment]
Hi @lex111 thank you for expressing your interest in helping us translate this tutorial!
An example of where one of our tutorials has been translated is:
https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server
where the file [`README.ko.md`](https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server/blob/master/README.ko.md) corresponds to the Korean translation of [`README.md`](https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server/blob/master/README.md) (the english version)

Essentially, go through the english 
and make your best effort to translate `README.md` to `README.ru.md`
If the UI for Travis-CI does not have a Russian version, simply "recycle" the English screenshots.

If you have any questions along the way. just post them here and we will try to help/clarify.

Спасибо! 🇷🇺 ☀️

**Comment by lex111** [comment]
@nelsonic sorry, I have not done the translation yet, but can I do the translation in my own repository (fork), in own README.md file, and you'll add a link to my translation in this repository, okay?

**Comment by lex111** [comment]
Just saw your approval in the form of emoticons, please next time _write_ in issue, because I can not track it by email :D

In other words, I can not find out about it until I look at the issue page...

**Comment by nelsonic** [comment]
@lex111 sounds good. thanks. 👍
