### ISSUE TITLE
travis-ci.org vs travis-ci.com?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-travis#60]
Travis can be used on two different domain name https://travis-ci.com/ and https://travis-ci.org/

- [ ] Explain what is the difference
- [ ] Describe how to let team members access the Travis settings of a repository with the Travis Github App

**Comment by eacdev** [comment]
touch .travis.yml && travis encrypt-file ./deploy_key --add

You have to add the --pro option to travis encrypt-file, or else you will get "iv undefined" error in your build.

**Comment by mambelli** [comment]
Travis CI originally created two separated platforms to differentiate between private repos / paid (travis-ci.com) and public repos / free (travis-ci.org).

However, as of May 2018, new users and projects (both private and public) should only use travis-ci.com (see the [official announcement](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps))

So people should use always travis-ci.com. I found out about it on stackexchange: https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

**Comment by nelsonic** [comment]
Sadly, no longer relevant #51 -> #67
