### ISSUE TITLE
iv undefined error (with fix)

### ISSUE THREAD

**Issue by mvsrgc** [dwyl/learn-travis#61]
The document at: https://github.com/dwyl/learn-travis/blob/master/encrypted-ssh-keys-deployment.md#5-encrypt-the-private-key 

Does not indicate that you have to add the --pro option to travis encrypt-file. If you don't specify --pro, you will get "iv undefined" error during your build.

**Comment by nelsonic** [comment]
@eacdev thanks for opening this issue. 👍
This must have changed since we wrote the guide last year.

**Comment by 17602937887** [comment]
thanks!

**Comment by nelsonic** [comment]
No longer using `Travis-Ci` ... #51 -> #67
